# Generated by Django 3.1 on 2020-10-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='stage',
            field=models.IntegerField(),
        ),
    ]
