# Generated by Django 3.1 on 2020-10-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201009_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='msg',
        ),
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.TextField(blank=True, default='Your address'),
        ),
    ]
