# Generated by Django 3.1 on 2020-10-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201009_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('msg', models.TextField(blank=True, default='-')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='msg',
            field=models.TextField(blank=True, default='-'),
        ),
    ]
